[package]
name = "auth-service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "^0.8"
tokio = { version = "1.48", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
chrono = "0.4"
